//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PENPAL.DataStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class cometchat_recentconversation
    {
        public string convo_id { get; set; }
        public int id { get; set; }
        public int from { get; set; }
        public int to { get; set; }
        public string message { get; set; }
        public string sent { get; set; }
    }
}
