//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PENPAL.DataStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class newsFeed
    {
        public long feedID { get; set; }
        public long userID { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public bool isApproved { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<long> created_by { get; set; }
        public Nullable<System.DateTime> modified_at { get; set; }
        public Nullable<long> modified_by { get; set; }
    }
}
