//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PENPAL.DataStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class OTPTransaction
    {
        public long OTPTransactionID { get; set; }
        public Nullable<long> UserId { get; set; }
        public string OTP { get; set; }
        public Nullable<bool> isVerified { get; set; }
        public Nullable<System.DateTime> VerifiedDateTime { get; set; }
    }
}
