//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PENPAL.DataStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class StellarMasterUser
    {
        public long Id { get; set; }
        public string PublicKey { get; set; }
        public string SecretKey { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
