//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PENPAL.DataStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionRangeCharge
    {
        public long Id { get; set; }
        public string Range { get; set; }
        public Nullable<long> Fee_Lumen_ { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<long> min { get; set; }
        public Nullable<long> max { get; set; }
    }
}
