//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PENPAL.DataStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionSetting
    {
        public long Id { get; set; }
        public Nullable<long> TransactionPerDay { get; set; }
        public Nullable<long> TransactionPerMonth { get; set; }
        public string ServiceTaxPerTransaction { get; set; }
        public Nullable<decimal> MinimumAmountForTransaction { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> PayPalMargin { get; set; }
        public Nullable<bool> EnableAddPayPal { get; set; }
        public Nullable<bool> EnableWithdrawPayPal { get; set; }
        public Nullable<int> CoinbaseMargin { get; set; }
        public Nullable<bool> EnableAddCoinbase { get; set; }
        public Nullable<int> CoinbaseSendLimit { get; set; }
        public Nullable<decimal> MinimumAmountForPayPalTransaction { get; set; }
    }
}
