//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PENPAL.DataStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class trnUserTransactionDetail
    {
        public long ID { get; set; }
        public Nullable<long> SenderUserId { get; set; }
        public Nullable<long> ReceiverUserId { get; set; }
        public string Amount { get; set; }
        public string Currency { get; set; }
        public string SenderPublicKey { get; set; }
        public string SenderSecretKey { get; set; }
        public string ReceiverPublicKey { get; set; }
        public Nullable<long> TXNID { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> TXNDATE { get; set; }
        public string PAYMENTMODE { get; set; }
        public Nullable<bool> ISTXNVERIFIED { get; set; }
    }
}
