//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PENPAL.DataStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class trnUserTransactionSetting
    {
        public long Id { get; set; }
        public Nullable<long> UserId { get; set; }
        public Nullable<long> TransactionPerDay { get; set; }
        public Nullable<decimal> TransactionAmountPerDay { get; set; }
    }
}
